# Site settings
title: DisneyWorldMan - Official Site
email: bradykondek@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  The official website of DisneyWorldMan
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.disneyworldman.ga" # the base hostname & protocol for your site
#twitter_username:
#github_username:  

# Build settings
markdown: kramdown
